name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  # file name consistency
  test_filenames:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout testfiles repository
      uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: 3.8
    - name: Test repository files
      run: python .github/check_sample_filenames.py .
  # to allow quicker tests, capa should run less than THRESHOLD seconds on added/modified test files
  test_runtime:
    runs-on: ubuntu-20.04
    steps:
    # We check the submodules separately as the rules submodule's reference may not be our PR/master
    - name: Checkout capa without submodules
      uses: actions/checkout@v3
      with:
        repository: mandiant/capa
    - name: Checkout capa-rules
      uses: actions/checkout@v3
      with:
        repository: mandiant/capa-rules
        path: rules
    - name: Checkout capa-testfiles
      uses: actions/checkout@v3
      with:
        path: tests/data
    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: 3.8
    - name: Install capa
      run: pip install -e .
    - name: Get modified files
      id: files
      uses: Ana06/get-changed-files@v2.2.0
    - name: Check capa runtime on modified files
      run: |
        cd tests/data
        python .github/check_runtimes.py ${{ steps.files.outputs.all }}
